services:
  nginx:
    image: nginx:stable
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - frontend
      #- homepage
      - portainer
      - calibre
      - calibre-web
      - mealie
      - nextcloud-aio
      - radarr
      - sonarr
      - watchtower
  certbot:
    image: certbot/dns-cloudflare:latest
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/lib/:/var/lib/letsencrypt:rw
      - ./cloudflare.ini:/etc/letsencrypt/cloudflare.ini:ro
    command: >-
      certonly --dns-cloudflare
      --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini
      --dns-cloudflare-propagation-seconds 15
      --email tylerclark2@gmail.com
      --agree-tos --no-eff-email
      --force-renewal
      -d tyler-clark.com
      -d *.tyler-clark.com

networks:
  frontend:
    external: true
    #name: frontend
  homepage:
    external: true
    name: homepage
  portainer:
    external: true
    name: portainer
  calibre-web:
    external: true
    name: calibre-web
  calibre:
    external: true
    name: calibre
  nextcloud-aio:
    external: true
    name: nextcloud-aio
  mealie:
    external: true
    name: mealie
  radarr:
    external: true
    name: radarr
  sonarr:
    external: true
    name: sonarr
  watchtower:
    external: true
    name: watchtower
