services:
  nginx:
    image: nginx:stable
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www/:/var/www/certbot/:ro
    networks:
      - calibre
      - homepage
      - portainer
      - radarr
      - radarr_swarm
      - sonarr
      - mealie
      - nextcloud
      - pasta
      - tdarr
      - tautulli
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/lib/:/var/lib/letsencrypt:rw

networks:
  calibre:
    external: true
    name: calibre
  homepage:
    driver: overlay
    external: true
    name: homepage
  portainer:
    external: true
    name: portainer
  sonarr:
    external: true
    name: sonarr
  radarr:
    external: true
    name: radarr
  radarr_swarm:
    name: radarr_swarm
    external: true
  mealie:
    driver: overlay
    external: true
    name: mealie
  nextcloud:
    external: true
    name: nextcloud
  pasta:
    driver: overlay
    external: true
    name: pasta
  tdarr:
    external: true
    name: tdarr
  tautulli:
    driver: overlay
    external: true
    name: tautulli
