services:
  nginx:
    image: nginx:stable
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - homepage
      - portainer
      - mealie
      - nextcloud
      - nextcloud-aio
      - pasta
      - tautulli
  certbot:
    image: certbot/dns-cloudflare:latest
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/lib/:/var/lib/letsencrypt:rw
      - ./cloudflare.ini:/etc/letsencrypt/cloudflare.ini:ro

networks:
  homepage:
    driver: overlay
    external: true
    name: homepage
  portainer:
    external: true
    name: portainer
  nextcloud:
    driver: overlay
    external: true
    name: nextcloud
  nextcloud-aio:
    external: true
    name: nextcloud-aio
  mealie:
    driver: overlay
    external: true
    name: mealie
  pasta:
    driver: overlay
    external: true
    name: pasta
  tautulli:
    driver: overlay
    external: true
    name: tautulli
