services:
  nginx:
    image: nginx:stable
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - calibre
      - homepage
      - portainer
      - radarr
      - radarr_swarm
      - sonarr
      - mealie
      - nextcloud
      - tdarr
      - tautulli

networks:
  calibre:
    external: true
    name: calibre
  homepage:
    external: true
    name: homepage
  portainer:
    external: true
    name: portainer
  sonarr:
    external: true
    name: sonarr
  radarr:
    external: true
    name: radarr
  radarr_swarm:
    name: radarr_swarm
    external: true
  mealie:
    driver: overlay
    external: true
    name: mealie
  nextcloud:
    external: true
    name: nextcloud
  tdarr:
    external: true
    name: tdarr
  tautulli:
    external: true
    name: tautulli
