services:
  nginx:
    image: nginx:stable
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - default
      - nextcloud-aio
  certbot:
    image: certbot/dns-cloudflare:latest
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/lib/:/var/lib/letsencrypt:rw
      - ./cloudflare.ini:/etc/letsencrypt/cloudflare.ini:ro
    command: >-
      certonly --dns-cloudflare
      --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini
      --dns-cloudflare-propagation-seconds 15
      --email tylerclark2@gmail.com
      --agree-tos --no-eff-email
      --force-renewal
      -d tyler-clark.com
      -d *.tyler-clark.com

networks:
  default:
    external: true
    name: frontend
  nextcloud-aio:
    external: true
    name: nextcloud-aio
